### ISSUE TITLE
Readfile method problems

### ISSUE THREAD

**Issue by Miyukiichan** [BillC13/matrix2#4]
Exits unexpectedly. Instead, return an integer from that function indicating success/failure types. The calling parent can then decide what to do from there ie. cleanup before exit and print to the screen

There is also an unneccesary for loop and redeclared variables DONE

Also there's no default behaviour for matrix typy reading. If the type is not present or is incorrect, there is no indication of that on read DONE

**Comment by SamMatthews126** [comment]
All issues in here have been addressed
