### ISSUE TITLE
Add constructor overload for Matrix class

### ISSUE THREAD

**Issue by Miyukiichan** [BillC13/matrix2#6]
Have it take a string parameter for the filename and call readFile automatically. Alternatively, have one constructor that taks a string as an optional parameter and perform the readfile if the filename is passed (ie not an empty string). The former is preferable but either would be good.

**Comment by SamMatthews126** [comment]
This is actually a bad idea for if the file read goes wrong because internal readfile call cannot return failure indicator to the parent
