### ISSUE TITLE
Additional readfile issues

### ISSUE THREAD

**Issue by Miyukiichan** [BillC13/matrix2#8]
There are two points where the function returns 0 upon successful read. This is unnecessary. Just return 0 at the end. Also these returns result in the file not getting closed.

Also, after the first check, the rest of the function is enclosed in an else block. This is also unnecessary as the return inside the previous if will exit the function.

Also the return 2 doesn't have the file closure before it either.

**Comment by SamMatthews126** [comment]
This is done
